title: Rapidmod.io
email: support@rapidmod.github.io
description: Product showcase, blog, and multimedia guides.
baseurl: "" 
url: "https://rapidmod.github.io"

collections:
  products:
    output: true
  instructions:
    output: true

markdown: kramdown
remote_theme: jekyll/minima
