title: Rapidmod.io
email: support@yrapidmod.github.io
description: Product showcase, blog, and multimedia guides.
baseurl: "" # leave empty for github.io
url: "https://rapidmod.github.io"

# Define Collections for Products and Instructions
collections:
  products:
    output: true
  instructions:
    output: true

markdown: kramdown
theme: minima # A reliable, clean starting theme